FROM python:3.10

EXPOSE 6002

RUN mkdir -p /opt/services/bot/my-bot
WORKDIR /opt/services/bot/my-bot

COPY . /opt/services/bot/my-bot/

RUN pip install -r requirements.txt

CMD ["python", "/opt/services/bot/my-bot/main.py"]
